# config.py
"""
Central configuration for the Swing Options Bot
Tuned for a \~$13,000 account
"""

# Account & Risk
ACCOUNT_SIZE = 13000
MAX_RISK_PER_TRADE_PCT = 0.015          # 1.5% of account
MAX_RISK_PER_TRADE_USD = ACCOUNT_SIZE * MAX_RISK_PER_TRADE_PCT   # \~$195
MAX_OPEN_POSITIONS = 5
MAX_HOLDING_DAYS = 25

# Universe
MIN_PRICE = 15.0
MIN_AVG_VOLUME = 750_000
MIN_MARKET_CAP = 2_000_000_000          # $2B

# Technical Parameters
EMA_FAST = 50
EMA_SLOW = 200
RSI_PERIOD = 14
RSI_BULL_LOW = 40
RSI_BULL_HIGH = 65
RSI_BEAR_LOW = 35
RSI_BEAR_HIGH = 60
ATR_PERIOD = 14
ATR_STOP_MULTIPLIER = 1.8
VOLUME_MA_PERIOD = 20

# Options Preferences
PREFERRED_DTE_MIN = 25
PREFERRED_DTE_MAX = 55
TARGET_DELTA_CALL = 0.40               # slightly ITM/OTM
TARGET_DELTA_PUT = -0.40
MAX_BID_ASK_SPREAD_PCT = 0.08          # 8%

# Scoring Weights (must sum to 1.0)
WEIGHT_FUNDAMENTAL = 0.30
WEIGHT_TREND = 0.20
WEIGHT_SETUP = 0.25
WEIGHT_OPTIONS = 0.15
WEIGHT_RR = 0.10

# Score Thresholds
MIN_SCORE_TO_TRADE = 55
ELITE_SCORE = 85
STRONG_SCORE = 70